rumpbake/rumpconfig: Add support for baked-in root filesystem

diff --git a/app-tools/rumpbake b/app-tools/rumpbake
--- a/app-tools/rumpbake
+++ b/app-tools/rumpbake
@@ -41,7 +41,7 @@ fi
 usage ()
 {
 	cat <<EOM
-usage: rumpbake TARGET OUTPUT FILE
+usage: rumpbake [ -v ] [ -R PATH ] TARGET OUTPUT FILE
        rumpbake list
 
 When invoked the single argument "list", lists supported target boards.
@@ -50,6 +50,12 @@ Else, creates a rumprunnable unikernel:
 	TARGET: rumprun board configuration to use.
 	OUTPUT: output file name for the unikernel image.
 	FILE: 	executable to bake.
+
+The -R option will add the contents of PATH to an in-memory root filesystem
+baked into the unikernel. This option may be specified multiple times, in
+this case the contents of all specified PATHs will be included.
+
+The -v option bakes verbosely.
 EOM
 	exit 1
 }
@@ -63,6 +69,24 @@ fi
 . ${CONF}
 
 CONFIG=
+
+ROOTFSPATHS=
+V=
+while getopts "vR:" opt; do
+	case "${opt}" in
+	R)
+		if [ ! -d ${OPTARG} ]; then
+			echo "rumpbake: error: -R ${OPTARG}: not a directory"
+			exit 1
+		fi
+		ROOTFSPATHS="${ROOTFSPATHS} ${OPTARG}"
+		;;
+	v)
+		V=yes
+		;;
+	esac
+done
+shift $((${OPTIND}-1))
 
 TARGET="${1}"
 if [ "${TARGET}" = "list" ]; then
@@ -97,12 +121,50 @@ for component in ${CONFIG}; do
 done
 
 # Check if the file is a relocatable object produced by a rumprun toolchain
+if [ ! -f ${FILE} ]; then
+	echo "rumpbake: error: ${FILE}: file does not exist"
+	exit 1
+fi
 if ! grep -q __RuMpRuN_fermented__ ${FILE}; then
 	echo "rumpbake: error: ${FILE}: not a rumprun relocatable object"
 	exit 1
 fi
 
+# Build root filesytem to bake into image if requested.
+if [ -n "${ROOTFSPATHS}" ]; then
+	TEMPDIR=$(mktemp -d)
+	ROOTFSTAR=${TEMPDIR}/rootfs.tar
+	ROOTFSOBJ=${TEMPDIR}/rootfs.tar.o
+	if [ -n "$V" ]; then
+		TAROPT=-vv
+	else
+		TAROPT=
+	fi
+	# Append contents of each PATH to the rootfs.tar.
+	# XXX: This will create multiple entries for ".".
+	for path in ${ROOTFSPATHS}; do
+		[ -n "$V" ] && echo "Adding ${path}:"
+		tar -C ${path} ${TAROPT} -rf ${ROOTFSTAR} .
+	done
+	# Symbol naming in the "binary" output format depends on the absolute
+	# file name being created; hence 'ld' must be run in the directory
+	# containing rootfs.tar.
+	(
+	cd ${TEMPDIR} &&
+	ld -r -o rootfs.tar.o -z noexecstack --format=binary rootfs.tar
+	)
+	objcopy --rename-section \
+		.data=.rodata,alloc,load,readonly,data,contents ${ROOTFSOBJ}
+else
+	ROOTFSOBJ=
+	TEMPDIR=
+fi
+
 # Final link using cc to produce the unikernel image.
-${APP_TOOLS_DIR}/${TOOLCHAIN}-cc \
-	-bake -o ${OUTPUT} ${FILE} -Wl,--whole-archive ${LIBS} \
-	|| exit 1
+LINK="${APP_TOOLS_DIR}/${TOOLCHAIN}-cc \
+	-bake -o ${OUTPUT} ${FILE} ${ROOTFSOBJ} -Wl,--whole-archive ${LIBS}"
+[ -n "$V" ] && echo "Link command: ${LINK}"
+${LINK}
+RESULT=$?
+[ -n "${TEMPDIR}" -a -d "${TEMPDIR}" ] && rm -rf ${TEMPDIR}
+exit ${RESULT}
